---
# tasks file for roles/container_deploy

- name: "Remove each container if it exists"
  ansible.builtin.command: "{{ container_executable }} rm -f {{ item.name }}"
  failed_when: false
  changed_when: false
  loop: "{{ containers_config }}"

- name: "Run each container"
  ansible.builtin.command: >
    {{ container_executable }} run -d 
    -p {{ item.external_port }}:{{ item.internal_port }} 
    --name {{ item.name }} 
    --restart unless-stopped 
    {{ registry_host }}/{{ item.name }}:latest
  loop: "{{ containers_config }}"
