---

- name: Verifica se è installato Docker
  ansible.builtin.command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false


- name: Versifica se è installato Podman
  ansible.builtin.command: podman --version
  register: podman_check
  failed_when: false
  changed_when: false


- name: Configrazione fact stato container
  ansible.builtin.set_fact:
    docker_available: "{{ docker_check.rc == 0 }}"
    podman_available: "{{ podman_check.rc == 0 }}"


- name: Determina quale programma utilizzare
  ansible.builtin.set_fact:
    container_executable: "{{ 'podman' if (podman_available and container_engine_force == 'auto') or container_engine_force == 'podman' else 'docker' }}"

- name: Mostra il programma di container selezionato
  ansible.builtin.debug:
    msg: "Il programma di container selezionato è: {{ container_executable }}"