---
- name: Build di Immagini Container OS differenti con SSH
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Genera la coppia di chiavi SSH usando il comando di sistema
      ansible.builtin.command:
        cmd: ssh-keygen -t rsa -b 4096 -C "genericuser@example.com" -f ./id_key_genericuser -N ""
        creates: ./id_key_genericuser

    - name: Build dell'immagine Ubuntu con Podman
      containers.podman.podman_image:
        name: localhost/ssh-ubuntu
        tag: latest
        path: .
        state: build
        build:
          file: Dockerfile.ubuntu

    - name: Build dell'immagine Debian con Podman
      containers.podman.podman_image:
        name: localhost/ssh-debian
        tag: latest
        path: .
        state: build
        build:
          file: Dockerfile.debian