---
- name: Copia Backup su Target
  hosts: target
  become: true

  tasks: 
    - name: copia Backup
      ansible.builtin.copy:
        src: ../backups/testdb_backup.sql
        dest: /tmp/testdb_backup.sql
       