---
- name: Recupero backup
  hosts: source
  become: true

  tasks:
    - name: Copia Backup
      ansible.builtin.fetch:
        src: /tmp/testdb_backup.sql
        dest: "{{ playbook_dir }}/../backups/testdb_backup.sql"
        flat: true