---
- name: Installazione MariaDB
  hosts: all
  become: true

  tasks:
    - name: Installa MariaDB con client
      ansible.builtin.apk:
        name:
          - mariadb-client
          - mariadb
        state: present
        update_cache: true
    
    - name: Inizializza MariaDB
      ansible.builtin.command:
        cmd: mariadb-install-db --user=mysql --datadir=/var/lib/mysql
        creates: /var/lib/mysql/mysql
      

    - name: Avvia MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true