---
- name: Database Restore
  hosts: target
  become: true

  vars_files:
    - vault.yml

  tasks:
    - name: Crea testdb
      ansible.builtin.shell: |
        mariadb -u  "{{ db_user }}" -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"


    - name: Restore Backup
      ansible.builtin.shell: |
        mariadb -u "{{ db_user}}"  "{{ db_name }}" < /tmp/testdb_backup.sql