[deploy_servers]
deploy_target ansible_host=localhost ansible_port=2223

[deploy_servers:vars]
ansible_user=root
ansible_password="{{ lookup('ansible.builtin.env', 'DEPLOY_TARGET_PASSWORD') }}"
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
